### PR TITLE
Weekly triggering of nightlies?

### PR DESCRIPTION
**Pull request by mareknovotny**
Every Wednesday

Changing the triggering of prod nightlies to Wednesdays ONLY?

### CODE REVIEW

**Review by domhanak — APPROVED** [review]
+1

**Comment by rgdoliveira** [comment]
This will disable all nightlies, not just RHPAM. As we discussed in chat probably the best approach is to split this pipeline in 2 - one for legacy product and other for not legacy products - and then we can properly adjust the cron for each of them.

**Comment by mareknovotny** [comment]
i cloned the `job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy` into rhpam/bamoe one fyi @rgdoliveira @domhanak

**Review by domhanak — APPROVED** [review]

**Comment by mareknovotny** [comment]
ok, so i will merge it now. Is it ok for you @rgdoliveira ?

**Pull request merged**
