### PR TITLE
[BXMSPROD-1960] RHBOP: split quarkus core and platform version

### PR DESCRIPTION
**Pull request by lampajr**
**Thank you for submitting this pull request**

Since Quarkus 2.13.x, core and platform artifacts could be different each other - for this reason we split versions in:
- `platform.quarkus.bom`
- `quarkus.bom` 

**JIRA**: 

https://issues.redhat.com/browse/BXMSPROD-1960

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by lampajr** [comment]
Example:

```json
{
    "built_projects": ["drools","optaplanner","optaplanner-quickstarts","optaweb-vehicle-routing","jboss-integration/rhbop-optaplanner"],
    "version": {"rhbop":"8.33.0.ER1","optaplanner":"8.33.0.Final-redhat-00001","drools":"8.33.0.Final-redhat-00001","quarkus.bom":"2.13.5.Final-redhat-00003","platform.quarkus.bom":"2.13.5.SP1-redhat-00002"},
    "maven_repository_file_url": "...",
    "offliner_file_url": "...",
    "archives": "...",
    "sources": {
        "optaplanner": "...",
        "optaplanner-quickstarts": ".."
    }
}
```

FYI @dupliaka

**Comment by dupliaka** [comment]
Looks fine for me. Quarkus versions could be aligned during CR build

**Review by rgdoliveira — APPROVED** [review]

**Comment by lampajr** [comment]
> Quarkus versions could be aligned during CR build

@dupliaka maybe yes, it depends on Quarkus side :)

**Comment by lampajr** [comment]
Just changed the commit in order to mention the linked Jira

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
